// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oggaljdxefwknoosmyub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nZ2FsamR4ZWZ3a25vb3NteXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzE0MzksImV4cCI6MjA3MjMwNzQzOX0._-BHqabXkPCNpBrZs2uZTqjNWdQgNUleIwiM9H1Ctgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});